version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME : admin
      MONGO_INITDB_ROOT_PASSWORD : password
    ports:
      - 27017:27017
  mongo-exp:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : admin
      ME_CONFIG_MONGODB_ADMINPASSWORD : password
      ME_CONFIG_MONGODB_SERVER : mongo
    ports:
      - 8081:8081

