version: '3.1'

services:
  my-mongo-app:
    image: 065642457853.dkr.ecr.ap-south-1.amazonaws.com/my-mongo-app:1.1
    ports:
      - 3000:3000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME : admin
      MONGO_INITDB_ROOT_PASSWORD : password
    ports:
      - 27017:27017
  mongo-exp:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME : admin
      ME_CONFIG_MONGODB_ADMINPASSWORD : password
      ME_CONFIG_MONGODB_SERVER : mongo
    ports:
      - 8081:8081
